[package]
name = "wheel-of-names"
version = "0.1.0"
authors = ["Joxtacy <10127673+Joxtacy@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
rand = "0.8.5"
ratatui = "0.27.0"
